language: python
python:  
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements/dev.txt
# command to run tests
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/pystro.py"
  - export FLASK_DEBUG=1

script: 
  - nosetests